//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ismailaktas.Models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ismailak1_Entities4 : DbContext
    {
        public ismailak1_Entities4()
            : base("name=ismailak1_Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tablo_Kategoriler> Tablo_Kategoriler { get; set; }
        public virtual DbSet<Tablo_Yemek> Tablo_Yemek { get; set; }
    }
}
