//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ismailaktas.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablo_Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tablo_Kategoriler()
        {
            this.Tablo_Yemek = new HashSet<Tablo_Yemek>();
        }
    
        public short kategoriid { get; set; }
        public string kategoriad { get; set; }
        public Nullable<byte> kategoriadet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tablo_Yemek> Tablo_Yemek { get; set; }
    }
}
