//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ismailaktas.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablo_Yemek
    {
        public short yemekid { get; set; }
        public string yemekad { get; set; }
        public string yemekmalzeme { get; set; }
        public string malzeme2 { get; set; }
        public string malzeme3 { get; set; }
        public string malzeme4 { get; set; }
        public string malzeme5 { get; set; }
        public string malzeme6 { get; set; }
        public string yemektarifi { get; set; }
        public short kategoriid { get; set; }
        public string yemekresim { get; set; }
        public string yemeksure { get; set; }
    
        public virtual Tablo_Kategoriler Tablo_Kategoriler { get; set; }
    }
}
